services:
  - type: web
    name: metaconverter
    env: static
    buildCommand: ""
    staticPublishPath: ./
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
